package com.gmail.doctatyana1.warehouse_api.app;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        throw new UnsupportedOperationException();
    }
}
