package com.gmail.doctatyana1.warehouse_api.app;

/*
 * This Java source file was generated by the Gradle 'init' task.
 * Application entry point.
 */

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan("com.gmail.doctatyana1")
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
